### ISSUE TITLE
 size equivariance

### ISSUE THREAD

**Issue by shuida** [tscohen/GrouPy#14]
Hello Dr.Cohen, 
your group-conv is a great job to preserve rotatation and translation equivariance. I wonder if there is any work about size equivariance, assuming the feature maps and filters stored in infinite arrays.

**Comment by tscohen** [comment]
Hi Shuida,
There are some works that use filters at multiple scales (try searching for "multi scale convolutional networks"), but I don't think any of them are properly equivariant. Building scale-equivariant networks that are numerically stable and really improve performance is an important and challenging problem to work on.

**Comment by shuida** [comment]
I know about some work using multi-scale filters, which improving performance by choosing several discrete size. But they seem more like tricks rather than solving the problem in theory. If only the continuous size challenge could be overcome, the group-conv will be more perfect.

**Comment by tscohen** [comment]
I agree. Let me know if you solve it :)
