### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part

### ISSUE THREAD

**Issue by wgimmy** [tscohen/GrouPy#27]
Hi Dr Cohen
I am a newbie who just learned GCNN and I'm trying to run the test file "test_gfuncarray.py"but meet the title's error.The error in the title was reported when I calculated h*f. The error told me that the dimensions of self.v in the call method of GFuncArray may not match the index dimensions of inds. The shapes I printed out afterwards were as follows: inds shapes: [' Ellipsis', (4, 5, 5), (4, 5, 5), (4, 5, 5)], self.v shape: (2, 6, 4, 5, 5), I don’t understand gcnn yet How to make these two shapes match and why an error occurs? Is it because of the numpy version update? Can you please answer it for me?

**Comment by tscohen** [comment]
This is likely due to a version issue with one of the dependencies. Make sure to use the old versions from when this code was released (2016). In any case I recommend using another code base as this one is no longer maintained.
https://github.com/QUVA-Lab/escnn
https://e3nn.org/

**Comment by wgimmy** [comment]
thanks for answering,it helps me a lot！

Taco Cohen ***@***.***> 于2023年11月20日周一 05:17写道：
