### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by dqii** [tscohen/GrouPy#8]
Hi! I was wondering if the Tensorflow code was written for Python 2.7 or Python 3.
Currently, running the sample code I got no error with Python 2.7, but "ValueError: ("Size of label '%s' for operand %d does not match previous terms.", 'G', 1)" when running on Python3. 

Thank you!

**Comment by lgeiger** [comment]
You can try out https://github.com/ehoogeboom/hexaconv/pull/2 which works on Python 3. Happy to get more people trying it out.

**Comment by dqii** [comment]
I'll try it out, thank you! :) Glad it works in Tensorflow.
As a separate update, I had been using numpy 1.14.1 with my Python 2.7 environment and 1.14.0 with Python 3. Upgrading numpy addressed the issue.
